### PR TITLE
Start using sbt-ci-release

### PR DESCRIPTION
**Pull request by sideeffffect**
If you want, you can set up publishing to be done directly from GitHub Actions. It has many advantages:
 * more comfortable
 * publish version by only creating a release from GitHub web UI
 * SNAPSHOT	versions are published from `master`, so users won't have to nag you to make a release so that they can try out a feature

To do so, you'll have to add to GitHub Action secrets these environment variables as described in the tutorial: https://github.com/olafurpg/sbt-ci-release#secrets
 * `PGP_PASSPHRASE`
 * `PGP_SECRET`
 * `SONATYPE_PASSWORD`
 * `SONATYPE_USERNAME`

### CODE REVIEW

**Comment by sideeffffect** [comment]
Blocked on https://github.com/eikek/emil/pull/183

**Comment by eikek** [comment]
I'd love to have it this way! the more of these things being automated, the better.

Just to be sure: To do a release now; I need to push the tag *and* create a release in the webui? or is this already done with some action? Later I also need to push the microsite, this would still be done manually right?

**Comment by sideeffffect** [comment]
> Just to be sure: To do a release now; I need to push the tag and create a release in the webui? or is this already done with some action?

Creating a release creates a tag automatically. So after this PR is merged, just create a release, the fields will be already pre-populated :sunglasses: 

> Later I also need to push the microsite, this would still be done manually right?

Not yet (even after this PR is merged). But it can be automated. We could take inspiration from https://github.com/zio/zio or https://github.com/zio/zio-prelude

**Comment by eikek** [comment]
Thank you! I created the four secrets.

**Comment by sideeffffect** [comment]
Awesome, it seems like it's working :tada: 
https://github.com/eikek/emil/runs/2256992744?check_suite_focus=true#step:5:360

**Comment by eikek** [comment]
This is amazing! Thank you again! 👍🏼 👍🏼 👍🏼

**Pull request merged**
