### PR TITLE
Hide (possibly) many tests behind one `ci` job

### PR DESCRIPTION
**Pull request by sideeffffect**
This will allow Mergify to merge Scala Steward's PRs again (like https://github.com/eikek/emil/pull/185).

Btw @eikek , you should enable Renovate bot for this repository, if you haven't done so :wink: https://app.renovatebot.com/dashboard

### CODE REVIEW

**Comment by eikek** [comment]
Thanks @sideeffffect - I thought I'm using scalasteward for what would renovate do just the same no?

**Comment by sideeffffect** [comment]
Scala Steward is great for Scala related stuff (like sbt, Scalafmt, etc.), better than what Renovate could do. But it can't update versions of GitHub Actions tasks -- for that, we have Renovate :wink:

**Comment by eikek** [comment]
Ah, right, thank you for clarifying!

**Comment by sideeffffect** [comment]
Since this is merged, can you please mark `ci` and `Summary` (from Mergify) as the build steps Required in `master` branch protection settings?

**Comment by eikek** [comment]
> Since this is merged, can you please mark `ci` and `Summary` (from Mergify) as the build steps Required in `master` branch protection settings?

I'm not sure where to look. There are no branch rules in this project defined, if this is what you mean?

**Comment by sideeffffect** [comment]
Yes, it's good practice to have rule for `master` and allow only something which passed `ci` and `Summary`

image

**Comment by eikek** [comment]
Yes, I agree! Just didn't put that effort into emil yet :-) Thank you for pushing this and even more for guiding me! All these bots, apps, rules and yml files are making my head busy right now - but it's great to get the "automation award"! :-)

**Comment by eikek** [comment]
> Since this is merged, can you please mark `ci` and `Summary` (from Mergify) as the build steps Required in `master` branch protection settings?

Done.

**Pull request merged**
